### ISSUE TITLE
Error In CONSOLE

### ISSUE THREAD

**Issue by Janunez** [DRE2N/FactionsCosmetics#9]
When ever i would use an enchanted item with fire aspect two on a entity i would always get errors from console saying this below.
-------------------------------------------------------------------------------------------------------------------
[18:06:29 ERROR]: Could not pass event EntityCombustByEntityEvent to Factions v1.8.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1010) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1145) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1568) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDamageByEntityEvent.<init>(Lorg/bukkit/entity/Entity;Lorg/bukkit/entity/Entity;Lorg/bukkit/event/entity/EntityDamageEvent$DamageCause;I)V
        at com.massivecraft.factions.listeners.FactionsEntityListener.onEntityCombustByEntity(FactionsEntityListener.java:174) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-4741400-c1aa859]
        ... 17 more
-------------------------------------------------------------------------------------------------------------------

Please fix this.

**Comment by Sataniel98** [comment]
This is not the issue tracker of the plugin you're referring to
